apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xuangong-app.fullname" . }}
  labels:
    {{- include "xuangong-app.labels" . | nindent 4 }}
data:
  API_URL: {{ .Values.config.apiUrl | quote }}
